blank_issues_enabled: false
contact_links:
  - name: â“ Help and Support Discord Channel
    url: https://discord.com/channels/878764303052865537/900787619728871484
    about: Please ask and answer questions here. ğŸ¥
  - name: â“ Help and Support Gitter Channel
    url: https://gitter.im/vscode-marquee/community
    about: Please ask and answer questions here. ğŸ¥
